### PR TITLE
Fixed a bug related to app update and restart

### LINKED ISSUE #440: Spark operator broke on March 1
Hello there,

We're using `gcr.io/spark-operator/spark-operator:v2.4.0-v1beta1-latest` and the latest hash working for us is `5909b8e3bf817327a65ead7f8a89f04712dd4bff1ce56c6dd3a4c9d4fce2bdde` from 2019-01-31

With all other versions we're getting `"applicationState": {
            "errorMessage": "Driver Pod not found",
            "state": "RUNNING"
        }`
and are able to submit new applications, but not patching existing ones.

Has something changed in such a way we're now using it wrong ?

We're using the mutating admission webhook

Any chance you could also create tags for released versions so we're not forced using latest ?

Thanks !

### PR DESCRIPTION
**Pull request by liyinan926**
Fixes #440.

### CODE REVIEW

**Comment by liyinan926** [comment]
@skonto.

**Comment by skonto** [comment]
I tried the PR by submitting one and modifying the spec after that. It restarts the app. 
The description of the status is a bit not cleaned up when i do `kubectl describe sparkapplications...`:
Initial state reported:
```
Type    Reason                     Age                From            Message
----    ------                     ----               ----            -------
Normal  SparkApplicationAdded      33s (x2 over 36s)  spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
Normal  SparkApplicationSubmitted  33s                spark-operator  SparkApplication spark-pi was submitted successfully
Normal  SparkDriverRunning         27s                spark-operator  Driver spark-pi-driver is running
Normal  SparkExecutorPending       18s (x6 over 18s)  spark-operator  Executor spark-pi-1552739280689-exec-1 is pending
Normal  SparkExecutorPending       13s (x5 over 18s)  spark-operator  Executor spark-pi-1552739280689-exec-2 is pending
Normal  SparkExecutorRunning       7s (x5 over 13s)   spark-operator  Executor spark-pi-1552739280689-exec-1 is running
Normal  SparkExecutorRunning       7s (x3 over 12s)   spark-operator  Executor spark-pi-1552739280689-exec-2 is running
```
State after new spec mod:
```
Executor State:
  Spark - Pi - 1552739280689 - Exec - 1:  FAILED
  Spark - Pi - 1552739325723 - Exec - 1:  RUNNING
  Spark - Pi - 1552739325723 - Exec - 2:  RUNNING
Last Submission Attempt Time:             2019-03-16T12:28:47Z
Spark Application Id:                     spark-application-1552739336461
Submission Attempts:                      1
Termination Time:                         <nil>
Events:
Type    Reason                               Age                From            Message
----    ------                               ----               ----            -------
Normal  SparkApplicationAdded                90s (x2 over 93s)  spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
Normal  SparkApplicationSubmitted            90s                spark-operator  SparkApplication spark-pi was submitted successfully
Normal  SparkDriverRunning                   84s                spark-operator  Driver spark-pi-driver is running
Normal  SparkExecutorPending                 75s (x6 over 75s)  spark-operator  Executor spark-pi-1552739280689-exec-1 is pending
Normal  SparkExecutorPending                 70s (x5 over 75s)  spark-operator  Executor spark-pi-1552739280689-exec-2 is pending
Normal  SparkExecutorRunning                 64s (x3 over 69s)  spark-operator  Executor spark-pi-1552739280689-exec-2 is running
Normal  SparkExecutorRunning                 48s (x6 over 70s)  spark-operator  Executor spark-pi-1552739280689-exec-1 is running
Normal  SparkApplicationSpecUpdateProcessed  48s                spark-operator  Successfully processed spec update for SparkApplication spark-pi

```

**Comment by liyinan926** [comment]
There are two problems: 1) old executor state does not get cleared when the app is invalidated, and 2) no events get recorded for the new executors.

**Comment by skonto** [comment]
I still see the same issue:
```    Spark - Pi - 1552861711211 - Exec - 2:  FAILED
    Spark - Pi - 1552861741801 - Exec - 1:  COMPLETED
    Spark - Pi - 1552861741801 - Exec - 2:  RUNNING
  Last Submission Attempt Time:             2019-03-17T22:29:03Z
  Spark Application Id:                     spark-application-1552861757509
  Submission Attempts:                      1
  Termination Time:                         2019-03-17T22:31:05Z
Events:
  Type     Reason                               Age                    From            Message
  ----     ------                               ----                   ----            -------
  Normal   SparkApplicationAdded                3m27s (x2 over 3m30s)  spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
  Normal   SparkApplicationSubmitted            3m27s                  spark-operator  SparkApplication spark-pi was submitted successfully
  Normal   SparkDriverRunning                   3m21s                  spark-operator  Driver spark-pi-driver is running
  Normal   SparkExecutorPending                 3m17s (x6 over 3m17s)  spark-operator  Executor spark-pi-1552861711211-exec-1 is pending
  Normal   SparkExecutorPending                 3m12s (x5 over 3m17s)  spark-operator  Executor spark-pi-1552861711211-exec-2 is pending
  Normal   SparkExecutorRunning                 2m59s (x5 over 3m12s)  spark-operator  Executor spark-pi-1552861711211-exec-1 is running
  Normal   SparkExecutorRunning                 2m59s (x3 over 3m11s)  spark-operator  Executor spark-pi-1552861711211-exec-2 is running
  Normal   SparkApplicationSpecUpdateProcessed  2m59s                  spark-operator  Successfully processed spec update for SparkApplication spark-pi
  Warning  SparkApplicationPendingRerun         2m59s                  spark-operator  SparkApplication spark-pi is pending rerun
```
Also the driver completed but the status is never updated.

**Comment by skonto** [comment]
In another test where I apply three times the same thing:
```
kubectl  apply -f pi-metrics.yaml
sleep .5
kubectl  apply -f pi-metrics2.yaml
sleep .5
kubectl  apply -f pi-metrics3.yaml
```
 I get 

```
Status:
  Application State:
    Error Message:  
    State:          PENDING_RERUN
  Driver Info:
  Last Submission Attempt Time:  <nil>
  Termination Time:              <nil>
Events:
  Type     Reason                               Age                From            Message
  ----     ------                               ----               ----            -------
  Normal   SparkApplicationAdded                87s                spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
  Normal   SparkApplicationSpecUpdateProcessed  84s (x2 over 85s)  spark-operator  Successfully processed spec update for SparkApplication spark-pi
  Normal   SparkApplicationSubmitted            84s                spark-operator  SparkApplication spark-pi was submitted successfully
  Warning  SparkApplicationPendingRerun         3s (x8 over 83s)   spark-operator  SparkApplication spark-pi is pending rerun
```

File: pkg/controller/sparkapplication/controller.go [hunk 1]
```diff
@@ -507,15 +501,17 @@ func (c *Controller) syncSparkApplication(key string) error {
...
 		}
+		c.clearStatusWhenInvalidated(&appToUpdate.Status)
 		appToUpdate.Status.AppState.State = v1beta1.PendingRerunState
-		appToUpdate.Status.ExecutionAttempts = 0
 	case v1beta1.PendingRerunState:
 		if c.validateSparkResourceDeletion(appToUpdate) {
-			// Reset SubmissionAttempts count since this is a new overall run.
-			appToUpdate.Status.SubmissionAttempts = 0
-			appToUpdate.Status.TerminationTime = metav1.Time{}
+			c.recordSparkApplicationEvent(appToUpdate)
```
Comment (skonto) [inline pkg/controller/sparkapplication/controller.go]: Probably it would be good to run here `clearStatusWhenInvalidated` and `deleteSparkResources` to make sure just before each submission that we start fresh.

**Comment by skonto** [comment]
@liyinan926 what did you mean by 

> I'm not sure about problem though

**Comment by liyinan926** [comment]
> @liyinan926 what did you mean by
> 
> > I'm not sure about problem though
> 
> didnt get that.
> 
> IMHO we need either the integration tests or enhance a bit controler_test.go to cover multi-threaded scenarios since `syncSparkApplication` can be called in parallel, if not mistaken, due to multiple updates for example (btw i would also add a simple case where there are two consecutive updates).

I meant I'm not sure about the second problem.

File: pkg/controller/sparkapplication/controller.go (hunk 1 above)
Comment (liyinan926) [reply pkg/controller/sparkapplication/controller.go]: When the state is `PendingRerun`, we don't need to reset the status because the application is immediately submitted in that case and status is reset when the application gets submitted.

Comment (skonto) [reply pkg/controller/sparkapplication/controller.go]: I meant executor status. It seems that this is not enough as executor state is carried because exec pods left around from previous runs trigger updates when the app starts running.
Check the [log](https://gist.github.com/skonto/3705de9b88aa4830dac9506662fa82c3) for example these lines:
```
I0318 10:45:16.152909      11 event.go:221] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark", Name:"spark-pi", UID:"c9c55684-496a-11e9-91f6-0aee7538e092", APIVersion:"sparkoperator.k8s.io/v1beta1", ResourceVersion:"2196261", FieldPath:""}): type: 'Warning' reason: 'SparkExecutorFailed' Executor spark-pi-1552905893644-exec-1 failed
I0318 10:45:16.156769      11 controller.go:521] Trying to update SparkApplication spark/spark-pi, from: [{ 2019-03-18 10:45:16 +0000 UTC 0001-01-01 00:00:00 +0000 UTC {spark-pi-ui-svc 30545    } {SUBMITTED } map[] 1 1}] to [{spark-application-1552905905083 2019-03-18 10:45:16 +0000 UTC 0001-01-01 00:00:00 +0000 UTC {spark-pi-ui-svc 30545    spark-pi-driver} {SUBMITTED } map[spark-pi-1552905893644-exec-1:FAILED] 1 1}]
I0318 10:45:16.165868      11 sparkapp_metrics.go:144] Exporting metrics for spark-pi; old status: { 2019-03-18 10:45:16 +0000 UTC 0001-01-01 00:00:00 +0000 UTC {spark-pi-ui-svc 30545    } {SUBMITTED } map[] 1 1} new status: {spark-application-1552905905083 2019-03-18 10:45:16 +0000 UTC 0001-01-01 00:00:00 +0000 UTC {spark-pi-ui-svc 30545    spark-pi-driver} {SUBMITTED } map[spark-pi-1552905893644-exec-1:FAILED] 1 1}
I0318 10:45:16.165917      11 sparkapp_metrics.go:221] Exporting Metrics for Executor spark-pi-1552905893644-exec-1. OldState:  NewState: FAILED
I0318 10:45:16.165937      11 metrics.go:124] Decrementing spark_app_executor_running_count with labels map[app_type:Unknown] metricVal to 1
I0318 10:45:16.165955      11 controller.go:253] Ending processing key: "spark/spark-pi"
```
The old executor at some point triggers a pod update which triggers an app update, although a few lines above we have a new submit. State is different and syncSparkApplication make it become part of the app exec status and is never removed.  

Now regarding the event record. I added some logging in `getAndUpdateAppState`.

In the same scenario different run:
```
  Executor State:
    Spark - Pi - 1552909628546 - Exec - 2:  FAILED
    Spark - Pi - 1552909656575 - Exec - 1:  COMPLETED
    Spark - Pi - 1552909656575 - Exec - 2:  RUNNING
  Last Submission Attempt Time:             2019-03-18T11:47:38Z
  Spark Application Id:                     spark-application-1552909673112
  Submission Attempts:                      1
  Termination Time:                         2019-03-18T11:49:51Z
Events:
  Type     Reason                               Age                    From            Message
  ----     ------                               ----                   ----            -------
  Normal   SparkApplicationAdded                5m15s                  spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
  Normal   SparkExecutorPending                 5m2s (x2 over 5m2s)    spark-operator  Executor spark-pi-1552909576599-exec-1 is pending
  Normal   SparkExecutorPending                 5m2s                   spark-operator  Executor spark-pi-1552909576599-exec-2 is pending
  Normal   SparkExecutorRunning                 4m57s                  spark-operator  Executor spark-pi-1552909576599-exec-2 is running
  Normal   SparkExecutorRunning                 4m57s                  spark-operator  Executor spark-pi-1552909576599-exec-1 is running
  Warning  SparkExecutorFailed                  4m41s                  spark-operator  Executor spark-pi-1552909576599-exec-1 failed
  Warning  SparkExecutorFailed                  4m41s                  spark-operator  Executor spark-pi-1552909576599-exec-2 failed
  Normal   SparkExecutorPending                 4m26s (x2 over 4m26s)  spark-operator  Executor spark-pi-1552909607670-exec-1 is pending
  Normal   SparkApplicationSpecUpdateProcessed  4m24s (x2 over 4m44s)  spark-operator  Successfully processed spec update for SparkApplication spark-pi
  Warning  SparkApplicationPendingRerun         4m23s (x2 over 4m44s)  spark-operator  SparkApplication spark-pi is pending rerun
  Normal   SparkApplicationSubmitted            4m20s (x3 over 5m12s)  spark-operator  SparkApplication spark-pi was submitted successfully
  Normal   SparkExecutorPending                 4m20s (x3 over 4m26s)  spark-operator  Executor spark-pi-1552909607670-exec-2 is pending
  Normal   SparkDriverRunning                   4m14s (x3 over 5m6s)   spark-operator  Driver spark-pi-driver is running
  Normal   SparkExecutorPending                 4m11s (x2 over 4m11s)  spark-operator  Executor spark-pi-1552909628546-exec-1 is pending
```
Looking at the logs: 
```
I0318 11:47:19.705428      11 spark_pod_eventhandler.go:41] Pod spark-pi-1552909628546-exec-2 added in namespace spark.
I0318 11:47:19.705460      11 spark_pod_eventhandler.go:77] Enqueuing SparkApplication spark/spark-pi for app update processing.
I0318 11:47:19.705490      11 controller.go:246] Starting processing key: "spark/spark-pi"
I0318 11:47:19.705552      11 controller.go:300] getAndUpdateAppState spark-pi-1552909628546-exec-1 2019-03-18 11:47:19.705544594 +0000 UTC
I0318 11:47:19.705588      11 controller.go:300] getAndUpdateAppState spark-pi-1552909628546-exec-2 2019-03-18 11:47:19.705582392 +0000 UTC
I0318 11:47:19.705607      11 controller.go:305] getAndUpdateAppState record event spark-pi-1552909628546-exec-2 2019-03-18 11:47:19.705582392 +0000 UTC
```
The recording there is never shown in the description, weird.

Comment (liyinan926) [reply pkg/controller/sparkapplication/controller.go]: >  I think options are either block updates for old pods in getAndUpdateAppState or make sure all resources are removed before a new submission happens (probably too restrictive).

I think we need to have the concept of some submission ID that is unique to each submission, and then use it when listing pods or processing pod events. This submission ID gets added to the pods as a label.

Comment (liyinan926) [reply pkg/controller/sparkapplication/controller.go]: > The recording there for spark-pi-1552909628546-exec-2 is never shown in the event list weird. Shouldn't all the events be listed there?

Yes, this is weird. I cannot explain this given that the code does record events for the new executors.

**Comment by liyinan926** [comment]
@skonto I plan to commit this first to unblock users who rely on the update-and-rerun feature. I will create a separate PR to address the problem of dealing with old executor pod updates.

File: pkg/controller/sparkapplication/controller.go (hunk 1 above)
Comment (skonto) [reply pkg/controller/sparkapplication/controller.go]: > I think we need to have the concept of some submission ID that is unique to each submission, and then use it when listing pods or processing pod events. This submission ID gets added to the pods as a label.

That also will work assuming we know which is the current submission id when an a random update occurs.

Comment (liyinan926) [reply pkg/controller/sparkapplication/controller.go]: Yes, we will record the submission ID in `SparkApplicationStatus`.

Comment (liyinan926) [reply pkg/controller/sparkapplication/controller.go]: I added a call to `clearStatus` here also. PTAL.

Comment (skonto) [reply pkg/controller/sparkapplication/controller.go]: @liyinan926 it seems that it overcomes the issue with the updates:
```
Executor State:
    Spark - Pi - 1552944088510 - Exec - 1:  RUNNING
    Spark - Pi - 1552944088510 - Exec - 2:  COMPLETED
  Last Submission Attempt Time:             2019-03-18T21:21:30Z
  Spark Application Id:                     spark-application-1552944104139
  Submission Attempts:                      1
  Termination Time:                         2019-03-18T21:25:25Z
Events:
  Type     Reason                               Age                    From            Message
  ----     ------                               ----                   ----            -------
  Normal   SparkApplicationAdded                6m9s (x2 over 6m12s)   spark-operator  SparkApplication spark-pi was added, enqueuing it for submission
  Normal   SparkExecutorPending                 5m54s (x2 over 5m54s)  spark-operator  Executor spark-pi-1552944036721-exec-2 is pending
  Normal   SparkExecutorPending                 5m54s (x2 over 5m54s)  spark-operator  Executor spark-pi-1552944036721-exec-1 is pending
  Normal   SparkExecutorRunning                 5m49s                  spark-operator  Executor spark-pi-1552944036721-exec-1 is running
  Normal   SparkExecutorRunning                 5m49s                  spark-operator  Executor spark-pi-1552944036721-exec-2 is running
  Warning  SparkExecutorFailed                  5m38s                  spark-operator  Executor spark-pi-1552944036721-exec-2 failed
  Normal   SparkExecutorPending                 5m24s (x2 over 5m24s)  spark-operator  Executor spark-pi-1552944067633-exec-2 is pending
  Normal   SparkExecutorPending                 5m24s (x2 over 5m24s)  spark-operator  Executor spark-pi-1552944067633-exec-1 is pending
  Normal   SparkApplicationSpecUpdateProcessed  5m20s (x2 over 5m41s)  spark-operator  Successfully processed spec update for SparkApplication spark-pi
  Warning  SparkApplicationPendingRerun         5m20s (x2 over 5m41s)  spark-operator  SparkApplication spark-pi is pending rerun
  Normal   SparkApplicationSubmitted            5m17s (x3 over 6m9s)   spark-operator  SparkApplication spark-pi was submitted successfully
  Normal   SparkDriverRunning                   5m13s (x3 over 6m3s)   spark-operator  Driver spark-pi-driver is running
  Normal   SparkExecutorPending                 5m3s (x2 over 5m3s)    spark-operator  Executor spark-pi-1552944088510-exec-1 is pending
```
feel free to commit this one.
The weird thing is that only the `spark-pi-1552944088510-exec-1` events are shown although 
`spark-pi-1552944088510-exec-2` als was recorded:
```
I0318 21:21:44.521557      11 spark_pod_eventhandler.go:41] Pod spark-pi-1552944088510-exec-2 added in namespace spark.
I0318 21:21:44.521582      11 spark_pod_eventhandler.go:77] Enqueuing SparkApplication spark/spark-pi for app update processing.
I0318 21:21:44.521609      11 controller.go:246] Starting processing key: "spark/spark-pi"
I0318 21:21:44.521664      11 controller.go:298] getAndUpdateAppState spark-pi-1552944088510-exec-2 2019-03-18 21:21:44.52165929 +0000 UTC
I0318 21:21:44.521685      11 controller.go:304] getAndUpdateAppState record event spark-pi-1552944088510-exec-2 2019-03-18 21:21:44.52165929 +0000 UTC
I0318 21:21:44.521693      11 controller.go:846] Blabla: PENDING 2019-03-18 21:21:44.521690233 +0000 UTC
I0318 21:21:44.521723      11 controller.go:298] getAndUpdateAppState spark-pi-1552944088510-exec-1 2019-03-18 21:21:44.521717418 +0000 UTC
I0318 21:21:44.521756      11 event.go:221] Event(v1.ObjectReference{Kind:"SparkApplication", Namespace:"spark", Name:"spark-pi", UID:"ab428214-49c3-11e9-91f6-0aee7538e092", APIVersion:"sparkoperator.k8s.io/v1beta1", ResourceVersion:"2323655", FieldPath:""}): type: 'Normal' reason: 'SparkExecutorPending' Executor spark-pi-1552944088510-exec-2 is pending
I0318 21:21:44.526176      11 spark_pod_eventhandler.go:52] Pod spark-pi-1552944088510-exec-2 updated in namespace spark.
```

Comment (liyinan926) [reply pkg/controller/sparkapplication/controller.go]: Sounds good. Thanks!

**Comment by skonto** [comment]
@liyinan926 one other thing that came up to my mind is that if you set the pod name to a deterministic one we dont make sure everything is cleanedup so submit will fail.
