### PR TITLE
Fixed webhook

### LINKED ISSUE #335: webhook-service configuration via helm chart impacts mutating admission controller calls
**What happened:**
In an effort to make use of a configMap for metrics.properties the following was specified in the driver spec:
```
  driver:
    configMaps:
      - name: metricsproperties
        path: /home
```
However, the pod was launched without the configMap mounted.   The documentation states that the following:

> The Kubernetes Operator for "Apache Spark comes with an optional mutating admission webhook for customizing Spark driver and executor pods based on the specification in SparkApplication objects, e.g., mounting user-specified ConfigMaps and volumes, and setting pod affinity/anti-affinity, and adding tolerations.

By default the helm chart automatically sets up the webhook.  The old helm chart had the following name for the webhook service hardcoded:
https://github.com/helm/charts/commit/6b0bbba5ce479430949f50016281795ff31d945b#diff-2ecb319330580dabceaf98668ee5b316L125

This hardcoded value can also be found during the webhook-init job that calls /usr/bin/gencerts.sh which looks like this:
```
# Note the CN is the DNS name of the service of the webhook.
openssl req -new -key ${TMP_DIR}/server-key.pem -out ${TMP_DIR}/server.csr -subj "/CN=spark-webhook.${NAMESPACE}.svc" -config ${TMP_DIR}/server.conf
```
Updates to the helm chart break apiserver calls to the webhook service:
https://github.com/helm/charts/commit/6b0bbba5ce479430949f50016281795ff31d945b#diff-63733843ff7febc22d286c29b04fe34eR5
because the templated service name was set to be dynamic:
- If the mutatingwebhookconfiguration does not match the webhook service, the apiserver fails to make calls.
- if the certs that are generated do not match the name of the webhook service, the TLS handshake fails.

**Quick Fix**
Revert to using the hardcoded `spark-webhook` webhook service name and respective TLS cert generated CN `spark-webhook.${NAMESPACE}.svc`

### PR DESCRIPTION
**Pull request by yuchaoran2011**
This PR needs to be merged first and the image `gcr.io/spark-operator/spark-operator:v2.4.0-v1alpha1-latest` needs to be rebuilt and pushed. After that I'll make a PR with these [changes](https://github.com/helm/charts/compare/master...yuchaoran2011:fixwebhook) against helm/charts repo. Because only after the new image is pushed will the helm/charts CI pass on my PR.

I also made the MutatingWebhookConfiguration name configurable. We have a use case where two teams each has an operator instance running in their own namespace. The team who installs the operator later would override the webhook configuration of the team who deployed earlier.

Fixed #335

### CODE REVIEW

File: Dockerfile [hunk 1]
```diff
@@ -16,8 +16,8 @@
 
 ARG SPARK_IMAGE=gcr.io/spark-operator/spark:v2.4.0
 
-FROM golang:1.10.2-alpine as builder
-ARG DEP_VERSION="0.4.1"
+FROM golang:1.11.2-alpine as builder
+ARG DEP_VERSION="0.5.0"
```
Comment (skonto) [inline Dockerfile]: Is this safe enough?

File: Dockerfile [hunk 2]
```diff
@@ -16,8 +16,8 @@
 
 ARG SPARK_IMAGE=gcr.io/spark-operator/spark:v2.4.0
 
-FROM golang:1.10.2-alpine as builder
-ARG DEP_VERSION="0.4.1"
+FROM golang:1.11.2-alpine as builder
```
Comment (skonto) [inline Dockerfile]: Is this safe enough?

File: hack/gencerts.sh [hunk 3]
```diff
@@ -23,18 +23,19 @@ function usage {
   cat<< EOF
   Usage: $SCRIPT
   Options:
-  -h | --help               	   Display help information.
+  -h | --help               	 Display help information.
```
Comment (liyinan926) [inline hack/gencerts.sh]: The indention seems off here.

**Comment by liyinan926** [comment]
@yuchaoran2011 the latest image `gcr.io/spark-operator/spark-operator:v2.4.0-v1alpha1-latest` has been pushed.
