### PR TITLE
Logging info when resources associated with SparkApplication still exist

### LINKED ISSUE #2724: Controller report errors when reconcling a suspended SparkApplication
### What happened?

- [x] ✋ I have searched the open/closed issues and my issue is not listed.

When setting `.spec.suspend` of a running `SparkApplication` from `false` to `true`, the following errors show up in controller logs:

```text
2025-11-12T05:58:15.971Z    ERROR    sparkapplication/controller.go:793    Failed to confirm being deleted resources associated with SparkApplication    {"controller": "sp
ark-application-controller", "namespace": "spark", "name": "spark-pi-suspend", "reconcileID": "64ffd29a-97e0-4a59-9234-445cd449a5d5", "name": "spark-pi-suspend", "namespac
e": "spark", "state": "SUSPENDED", "error": "resources associated with SparkApplication still exist: spark/spark-pi-suspend"}
github.com/kubeflow/spark-operator/v2/internal/controller/sparkapplication.(*Reconciler).reconcileSuspendedSparkApplication.func1
    /workspace/internal/controller/sparkapplication/controller.go:793
k8s.io/client-go/util/retry.OnError.func1
    /go/pkg/mod/k8s.io/client-go@v0.32.5/util/retry/util.go:51
k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection
    /go/pkg/mod/k8s.io/apimachinery@v0.32.5/pkg/util/wait/wait.go:145
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff
    /go/pkg/mod/k8s.io/apimachinery@v0.32.5/pkg/util/wait/backoff.go:461
k8s.io/client-go/util/retry.OnError
    /go/pkg/mod/k8s.io/client-go@v0.32.5/util/retry/util.go:50
k8s.io/client-go/util/retry.RetryOnConflict
    /go/pkg/mod/k8s.io/client-go@v0.32.5/util/retry/util.go:104
github.com/kubeflow/spark-operator/v2/internal/controller/sparkapplication.(*Reconciler).reconcileSuspendedSparkApplication
    /workspace/internal/controller/sparkapplication/controller.go:770
github.com/kubeflow/spark-operator/v2/internal/controller/sparkapplication.(*Reconciler).Reconcile
    /workspace/internal/controller/sparkapplication/controller.go:234
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255
2025-11-12T05:58:15.971Z    ERROR    sparkapplication/controller.go:803    Failed to reconcile SparkApplication    {"controller": "spark-application-controller", "namespac
e": "spark", "name": "spark-pi-suspend", "reconcileID": "64ffd29a-97e0-4a59-9234-445cd449a5d5", "name": "spark-pi-suspend", "namespace": "spark", "error": "resources assoc
iated with SparkApplication still exist: spark/spark-pi-suspend"}
github.com/kubeflow/spark-operator/v2/internal/controller/sparkapplication.(*Reconciler).reconcileSuspendedSparkApplication
    /workspace/internal/controller/sparkapplication/controller.go:803
github.com/kubeflow/spark-operator/v2/internal/controller/sparkapplication.(*Reconciler).Reconcile
    /workspace/internal/controller/sparkapplication/controller.go:234
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Reconcile
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:119
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:334
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:294
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.4/pkg/internal/controller/controller.go:255
2025-11-12T05:58:15.971Z    INFO    sparkapplication/controller.go:234    Finished reconciling SparkApplication    {"controller": "spark-application-controller", "namespac
e": "spark", "name": "spark-pi-suspend", "reconcileID": "64ffd29a-97e0-4a59-9234-445cd449a5d5"}
```

### Reproduction Code

1. Submit a non-suspended `SparkApplication`.
2. Set `.spec.suspend` to `true` when the app is in `RUNNING` state.
3. Set `.spec.suspend` to `false` when the app is in `SUSPENDED` state.

### Expected behavior

Errors should not show up in controller logs.

### Actual behavior

_No response_

### Environment & Versions

- Kubernetes Version: `v1.33.3`
- Spark Operator Version: `v2.4.0-rc.0`
- Apache Spark Version: `3.5.5`

### Additional context

_No response_

### Impacted by this bug?

Give it a 👍 We prioritize the issues with most 👍

### PR DESCRIPTION
**Pull request by ChenYi015**
## Purpose of this PR

Close #2724.

**Proposed changes:**

- Remove unnecessary error logging for suspended SparkApplication reconciliation.

## Change Category

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that could affect existing functionality)
- [ ] Documentation update

### Rationale

- When the app is in `SUSPENDING` state, the controller sends requests to API server to delete resources like driver pod, server and ingress, then change the state to `SUSPENDED` state.
- But the driver pod can still exists when reconciling a `SUSPENDED` app, thus the erros will show up in controller logs.
- When the driver pod is actually deleted, the `SUSPENDED` app will be reconciled again. So it is fine to remove the error logging statements to suprress the errors.

## Checklist

- [x] I have conducted a self-review of my own code.
- [ ] I have updated documentation accordingly.
- [ ] I have added tests that prove my changes are effective or that my feature works.
- [x] Existing unit tests pass locally with my changes.

### CODE REVIEW

**Comment by ChenYi015** [comment]
cc @everpeace

File: internal/controller/sparkapplication/controller.go [hunk 1]
```diff
@@ -788,10 +788,6 @@ func (r *Reconciler) reconcileSuspendedSparkApplication(ctx context.Context, req
 						State: v1beta2.ApplicationStateResuming,
 					}
 				}
-			} else {
-				err := fmt.Errorf("resources associated with SparkApplication still exist: %s/%s", app.Namespace, app.Name)
-				logger.Error(err, "Failed to confirm being deleted resources associated with SparkApplication", "name", app.Name, "namespace", app.Namespace, "state", app.Status.AppState.State)
-				return err
```
Comment (nabuskey) [inline internal/controller/sparkapplication/controller.go:794]: We don't have to return error here, but I think it's better to at least log and indicate that associated resources exists instead of silently proceeding.

Comment (ChenYi015) [reply internal/controller/sparkapplication/controller.go:794]: Have replaced error logging with info logging to avoid printing stack trace.

**Review by everpeace — COMMENTED** [review]
Thank you for the catch! LGTM!

**Review by nabuskey — APPROVED** [review]
LGTM
